"""create ticket table

Revision ID: e3340d36f75b
Revises: 9d1e18c2b345
Create Date: 2026-10-07 18:47:47.190705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3340d36f75b'
down_revision: Union[str, Sequence[str], None] = '9d1e18c2b345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('BOXES', 'BILLS_PAYMENT', 'ACCOUNT_MANAGEMENT', name='servicetype'), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket'))
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.drop_table('ticket')
    # ### end Alembic commands ###
